version: '3.8'

services:
  redis-master:
    image: redis/redis-stack:latest
    container_name: redis-stack-master
    ports:
      - "6379:6379"     # Redis server
      - "8001:8001"     # RedisInsight UI (đi kèm Redis Stack)
    volumes:
      - ./master/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-net

  redis-replica:
    image: redis/redis-stack:latest
    container_name: redis-stack-replica
    depends_on:
      - redis-master
    ports:
      - "6380:6379"
    volumes:
      - ./replica/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
